import React from 'react'
import { Metadata } from 'next';
import MainContainer from '@/components/containers/MainContainer'

interface Props {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: "Umamusume Support Card Database - All Cards & Effects - Umemusume Deckbuilder",
  description: "Generated by create next app",
};

const layout = ({children}:Props) => {
  return (
    <MainContainer>
      {children}
    </MainContainer>
  )
}

export default layout